### ISSUE TITLE
Path of over 260 characters is not supported

### ISSUE THREAD

**Issue by pubsquash** [mkht/7ZipArchiveDsc#6] opened 2022-02-25 01:22 UTC
I have an Oracle package that I am trying to extract and it fails on one file, which has over 255 chars in length for the full path. Yes I could probably trim down the path to extract to, but that will not be future proof.

Error I get:

[[x7ZipArchive]x7ZipArchive_b9c366ec-18c4-4d1e-86ed-feca54f0e966_202202251202489510975] The file
"client\stage\Components\oracle.jdk\1.8.0.201.0\1\DataFiles\Expanded\filegroup3\lib\missioncontrol\plugins\com.jrockit.
mc.console.ui.notification_5.5.2.174165\com.jrockit.mc.console.ui.notification_contexts.xml" in the archive is not
exist in the destination folder

**Comment by pubsquash** [comment] 2022-02-25 01:25
Also change the error message into better English (in the archive **is** not exist in the destination folder) to **does**

**Comment by mkht** [comment] 2022-02-25 01:46
Thank you.
I will investigate the issue as soon as possible and try to fix it.

Thanks also for pointing out the English message. I'm not very good at English and use machine translation, so I'm very glad for your suggestion to fix it.

**Comment by pubsquash** [comment] 2022-02-25 01:50
No problem happy to help. Maybe something like this? 

$tParam = @{
            #Added support for long pathnames via unicode "[backslash][backslash]?[backslash]"
            LiteralPath = "[backslash][backslash]?[backslash]$AbsolutePath"
            PathType    = $(if ($Item.ItemType -eq 'File') { 'Leaf' }else { 'Container' })
        }

**Comment by mkht** [comment] 2022-02-25 17:02
I have released v1.6.0, which fixes the issue, to PowerShell Gallary, please try it.
If the issue is still unresolved, please let me know.

This issue was actually occurring when the full path after expansion exceeded 260 characters. (not 255 characters)
I used your suggested approach of using `\\?\` prefix to fix it, but I needed to make a few more corrections in various codes.

I deeply appreciate that you reported this issue.
Thank you so much.

**Comment by pubsquash** [comment] 2022-02-28 01:22
Thanks for the update, still getting this when I *rerun *the DSC module.
When I run it the first time with no extracted data at the destination, it
works ok.

       x7ZipArchive Unzip
        {
            Destination =
'C:\Utilities\DSC\Source\b9c366ec-18c4-4d1e-86ed-feca54f0e966'
            Path        =
'C:\Utilities\DSC\Cache\b9c366ec-18c4-4d1e-86ed-feca54f0e966\DSC_Oracle_Client_19c_19.3.zip'
            Checksum    = "CRC32"
            Clean       = $true
            Validate    = $true
        }

PowerShell DSC resource x7ZipArchive  failed to execute Test-TargetResource
functionality with error message: The
running command stopped because the preference variable
"ErrorActionPreference" or common parameter is set to Stop:
The specified path, file name, or both are too long. The fully qualified
file name must be less than 260 characters,
and the directory name must be less than 248 characters.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**Comment by mkht** [comment] 2022-02-28 09:56
Hi @pubsquash 

I am not able to reproduce the same error as you. Can you provide a reproducible zip archive if possible?

Apart from that, in my testing, I noticed that there are many inadequacies regarding long path support.
I don't know why, but it seems that in some cases, code that works fine in the local PowerShell console does not work when run via DSC.

I will work on resolving this issue, but it may take some time as it may require more changes than expected.

**Comment by mkht** [comment] 2022-02-28 16:51
After some investigation, I found that `\\?\` pre-fixed paths (extended-length paths) are enabled in the PowerShell console, but not in the DSC engine.

For example, the following code executes a nearly equivalent process, but only in DSC it throws an exception.

#### Code for PowerShell console
```Powershell
$ExtendedPath = '\\?\C:\Test.txt'
New-Item -Path $ExtendedPath
```

#### Code for DSC
```PowerShell
Configuration test
{
    Script test1 {
        GetScript  = { @{} }
        SetScript  = { retrun $true }
        TestScript = {
            $ExtendedPath = '\\?\C:\Test.txt'
            New-Item -Path $ExtendedPath
        }
    }
}

test -outputpath C:\dsc
Start-DscConfiguration -Path C:\dsc -Force -Wait -Verbose
```

I am currently working on the implementation of the code to enable the extended path in DSC as well, and I hope to release it within the next few days.

**Comment by pubsquash** [comment] 2022-02-28 20:18
Awesome, thanks!

**Comment by pubsquash** [comment] 2022-03-01 06:56
Found a solution, but not sure if it will work, hope it helps you:

Configuration test
{

    Script test1 {
        GetScript  = { @{} }
        SetScript  = { return $true }
        TestScript = {

            Invoke-Command -ComputerName . -ScriptBlock {

                $ExtendedPath = '\\?\C:\Utilities\Test.txt'
                New-Item -Path $ExtendedPath

            }

        return $true

        }
    }
}

test -outputpath C:\dsc


Start-DscConfiguration -Path C:\dsc -Force -Wait -Verbose

**Comment by mkht** [comment] 2022-03-01 14:53
v1.7.0 is released with improved long path support.
I believe I have tested it thoroughly.
I hope this release can solve this issue completely.

Here is the code I tested.

### DSC test code
Tested in PowerShell 5.1 with Windows 10 x64 21H2 and PowerShell 5.0 with Windows 8.1 x86

```PowerShell
Configuration TestConf
{
    Import-DscResource -ModuleName 7ZipArchiveDsc

    $TooTooLongPath = (
        'm4GaCQ7tFKHar0ImHWywcq7BnwK3dCpJItP9n7qOzkAyXgu4G3i3drMkjpT0dsmucCbxQv5dRzRwgIy4A53BuZfQ3pZPKVpPiVpC5BqnAI6QAYfaQzs2rPfju2o69Zey6wJE9mljCk2b5g4fTHOoUwqB0ZXiIWgjDQPpJhc06F60kD42ci9Rkh7BP7v8RqEvdts5quLl5Hr9eYPPoUrzF9usV3zy4sKpxqVIUShYc6b8u6JKQaOgFbbaVOljxN',
        '1bfimhKYQr1BPFTBPoCxRzncFyIvk12EViXmq13j38cGySqnqbb5ozD2lH5Garu0YlnlB59QGmsPq6uPo5DbLs7O32UhhA3YPkxPSM3SwZsxUwg2dcnjuvkHtdGyNpvYJc4erITD1XU3pe8skMCDlwjxcWPY2Kfn5D4WdQrh8XPy8HJV8RM1Ul6pf6hrTMcwZqjPbiLzhdLNtCvhdHsKTsMHfhPsAdGXJQwmhEYLPtGbfiU9NufAWfoY0kTSEc',
        '1n6tBflSwlNxBNESwgZ3oFxK25F8nEy5JdtCElM4HzWUXZvG9wcBs0sYBbjQrpsNBrzxIcavnIAP5pc2JWtYQCtOQVFGoiFueAnw7NwTlD6GmivQN2uVRwOGBTm4t6KPpjLgMz5x14sRsMjzdFJyvNR6ilZ7JxP5LBfUVrHMOrc5zs3e16A4tZp7g64GfxtSPUmF3bP0WUW4IX8J7FwxmVIqVfbrU4eYLAGGvsCVeJbrTlBfYAPiSmCY5TUhoz',
        'dEqZH5pi6fnyRVbIqvVYfwRAwcy4tN4AwcUmSTUXfMlWi8oVI51LQg1EscBFxtDhGd5GcJGe4KBUps7lTObOmjZ8AVja41lr6WVZcQyFbuE4jUsjvFChZxpKNIU09EhvVOLSTC0M2PBCXUD1JnhnVEMXqS32TNcTohKZdjys7ASDSrSRHMSBAsRFenLGkRuMNetxqlZMFyNJZj2Xs4LH5mzaV2yAbjate5s6FUWBJZ7OnBiMwM1HMJXakQg0cg'
    ) -join '\'

    x7ZipArchive LongPathTest
    {
        Path        = "C:\eclipse-java-2021-12-R-win32-x86_64.zip"
        Destination = "C:\Destination\$TooTooLongPath"
        Validate    = $true
        Checksum    = 'CRC'
        Clean       = $true
    }
}

TestConf -outputpath C:\dsc
Start-DscConfiguration -Path C:\dsc -Force -Wait -Verbose
Test-DscConfiguration -Path C:\dsc -Verbose
```

### Console test code
Tested in PowerShell 5.1 and PowerShell 7.2.1 with Windows 10 x64 21H2

```PowerShell
$TooTooLongPath = (
    'm4GaCQ7tFKHar0ImHWywcq7BnwK3dCpJItP9n7qOzkAyXgu4G3i3drMkjpT0dsmucCbxQv5dRzRwgIy4A53BuZfQ3pZPKVpPiVpC5BqnAI6QAYfaQzs2rPfju2o69Zey6wJE9mljCk2b5g4fTHOoUwqB0ZXiIWgjDQPpJhc06F60kD42ci9Rkh7BP7v8RqEvdts5quLl5Hr9eYPPoUrzF9usV3zy4sKpxqVIUShYc6b8u6JKQaOgFbbaVOljxN',
    '1bfimhKYQr1BPFTBPoCxRzncFyIvk12EViXmq13j38cGySqnqbb5ozD2lH5Garu0YlnlB59QGmsPq6uPo5DbLs7O32UhhA3YPkxPSM3SwZsxUwg2dcnjuvkHtdGyNpvYJc4erITD1XU3pe8skMCDlwjxcWPY2Kfn5D4WdQrh8XPy8HJV8RM1Ul6pf6hrTMcwZqjPbiLzhdLNtCvhdHsKTsMHfhPsAdGXJQwmhEYLPtGbfiU9NufAWfoY0kTSEc',
    '1n6tBflSwlNxBNESwgZ3oFxK25F8nEy5JdtCElM4HzWUXZvG9wcBs0sYBbjQrpsNBrzxIcavnIAP5pc2JWtYQCtOQVFGoiFueAnw7NwTlD6GmivQN2uVRwOGBTm4t6KPpjLgMz5x14sRsMjzdFJyvNR6ilZ7JxP5LBfUVrHMOrc5zs3e16A4tZp7g64GfxtSPUmF3bP0WUW4IX8J7FwxmVIqVfbrU4eYLAGGvsCVeJbrTlBfYAPiSmCY5TUhoz',
    'dEqZH5pi6fnyRVbIqvVYfwRAwcy4tN4AwcUmSTUXfMlWi8oVI51LQg1EscBFxtDhGd5GcJGe4KBUps7lTObOmjZ8AVja41lr6WVZcQyFbuE4jUsjvFChZxpKNIU09EhvVOLSTC0M2PBCXUD1JnhnVEMXqS32TNcTohKZdjys7ASDSrSRHMSBAsRFenLGkRuMNetxqlZMFyNJZj2Xs4LH5mzaV2yAbjate5s6FUWBJZ7OnBiMwM1HMJXakQg0cg'
) -join '\'

Expand-7ZipArchive -Path "C:\eclipse-java-2021-12-R-win32-x86_64.zip" -Destination "C:\Destination2\$TooTooLongPath" 
```

**Closed as completed** 2022-03-09 11:50 UTC

**Comment by pubsquash** [comment] 2022-03-09 12:09
Thanks for your help. Worked
